+++
# About/Biography widget.

date = "2016-04-20T00:00:00"
draft = false

widget = "about"

# Order that this section will appear in.
weight = 1

# List your academic interests.
[interests]
  interests = [
    "Computational Statistics",
    "Spatio-temporal models",
    "Bayesian Inference"
  ]

# List your qualifications (such as academic degrees).
[[education.courses]]
  course = "PhD in Statistics and Agricultural Experimentation"
  institution = "Universidade de São Paulo"
  year = 2019

[[education.courses]]
  course = "MSc in Ecology"
  institution = "Universidade Federal de Santa Catarina"
  year = 2010

[[education.courses]]
  course = "BSc in Oceanography"
  institution = "Universidade do Vale do Itajaí"
  year = 2005

+++

# Biography

I'm a Researcher and Lecturer in the [Statistics Department][1] of the
Federal University of Paraná ([UFPR][8]), Brazil. I'am a member of the
Laboratory of Statistics and Geoinformation ([LEG][]), where I deal
mainly with statistical spatial models applied to environmental and
ecological problems, specially those dealing with marine fisheries
resources. I'm also a collaborator at the Laboratory of Environmental
Statistics ([LEA][]) of Federal University of Rio Grande ([FURG][]).

In 2019 I received a doctorate degree in [Statistics and Agricultural
Experimentation][] from University of São Paulo ([USP][11]), Brazil.
Originally, I have a bachelor degree in [Oceanography][3] from
University of Vale do Itajaí ([UNIVALI][9]), with a master's degree in
[Ecology][5] from Federal University of Santa Catarina ([UFSC][10]).

[1]: http://www.est.ufpr.br/
[2]: http://www.ufpr.br/
[LEG]: http://www.leg.ufpr.br/
[LEA]: http://www.imef.furg.br/index.php/laboratorios/12-lea.html
[FURG]: http://www.furg.br/
[3]: http://www.univali.br/oceano
[4]: http://www.univali.br/
[5]: http://poseco.ufsc.br
[6]: http://ufsc.br/
[Estatística e Experimentação Agronômica]: http://www4.esalq.usp.br/pg/programas/estatistica
[ESALQ]: http://www4.esalq.usp.br/
[7]: http://www5.usp.br/
[8]: https://issuu.com/ufprdigital/docs/ufpr_english
[9]: http://www.univali.br/english
[10]: http://en.ufsc.br
[Statistics and Agricultural Experimentation]: http://www.en.esalq.usp.br/graduate/programs/agricultural-statistics-and-experimentation
[11]: http://www5.usp.br/en/
