[build]
  command = "hugo --gc --minify -b https://fernandomayer.net"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b https://deploy-preview-1--fernandomayer.net"

[context.branch-deploy]
  command = "hugo --gc --minify -b https://deploy-preview-1--fernandomayer.net"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
