+++
date = "2016-08-26T00:00:00"
title = "Pesquisa reproduzível com R Markdown"
abstract = "Pesquisa reproduzível é a ideia geral onde análise de dados, e de maneira mais geral, descobertas científicas, devem ser publicadas contendo os dados e o código de análise, para que outras pessoas possam verificar os resultados e até mesmo continuar a construir ideias sobre eles. A importância de reproducibilidade na ciência é altamente reconhecida hoje em dia, mas ainda não é largamente praticada. Um dos motivos é que muitos cientistas não adotaram ainda as ferramentas necessárias para a pesquisa reproduzível. Esta apresentação mostrará ferramentas para análise estatística documentada, que permitem que cientistas publiquem suas análises em um documento auto-contido. Particularmente, será demonstrado como gerar relatórios dinâmicos com o R, através do pacote 'rmarkdown'. Alguns recursos relativamente novos disponíveis neste pacote também serão apresentados, demonstrando sua grande capacidade de se tornar uma ferramenta padrão para pesquisa reproduzível no R."
abstract_short = ""
event = "Meetup R users São Paulo"
event_url = "https://www.meetup.com/pt-BR/useR-SP/"
location = "São Paulo, Brasil"

selected = false
math = true

url_pdf = ""
url_slides = ""
url_video = ""

# Optional featured image (relative to `static/img/` folder).
[header]
image = ""
caption = ""

+++

Código fonte da apresentação disponível no [Github](https://github.com/fernandomayer/Rmarkdown-rautu).

{{< youtube UCzHmqVY0gA >}}
