+++
abstract = "At the breeding grounds of most baleen whales the patchiness and gaps in spatial distribution results from interactions between behavior patterns and environmental conditions. We evaluated the influence of environmental factors (bathymetry and distance from shore with quadratic terms, and wind speed), effort, and spatial autocorrelation effects to predict humpback whale group density in the Southwest Atlantic Ocean. Count data of groups by grid cells were fitted with conditional autoregressive models (CAR). Bayesian inference was performed via integrated nested Laplace approximation. The best-fit model contained distance from shore and its quadratic term, bathymetry, and the autoregressive component. Occupancy probability was high for the Abrolhos Bank, some cells from the northeast continental shelf and southeast margin, but gaps in occurrence were identified. High densities were estimated in the east continental margin, with the highest density in the Abrolhos Bank, in some cells of the northeast continental margin and in the southernmost area. We report that intermediate distances from the coast, and shallow waters were preferred for breeding and calving activities. We suggest that CAR models may incorporate aggregation mechanisms into habitat modeling and may provide advances in marine mammal analyses by accounting for residual autocorrelation."
abstract_short = ""
authors = ["HJ Pavanato", "FP Mayer", "LL Wedekin", "MH Engel", "PG Kinas"]
date = "2018-02-20"
image_preview = ""
math = true
publication_types = ["2"]
publication = "Marine Mammal Science"
publication_short = "MMS"
selected = false
title = "Prediction of humpback whale group densities along the Brazilian coast using spatial autoregressive models"
url_code = ""
url_dataset = ""
url_pdf = "http://onlinelibrary.wiley.com/doi/10.1111/mms.12492/epdf"
url_project = ""
url_slides = ""
url_video = ""

[[url_custom]]
name = "Publication page"
url = "http://onlinelibrary.wiley.com/doi/10.1111/mms.12492/abstract"

# Optional featured image (relative to `static/img/` folder).
[header]
image = ""
caption = ""

+++
