+++
abstract = "Global biodiversity declines and increasing rates of extinction necessitate the assessment and prediction of the vulnerability of species to extinction. Here, we examine the relationships between conservation status and ecological traits of reef fish species of the Brazilian biogeographical province. We used binomial tests and a logistic regression to address two questions. Do biological attributes differ between threatened and non-threatened fishes? Which combination of traits and impacts exerts greater influence on species threat status? Of the 559 species, 36 are categorized as threatened (compiled from global, national and local Red Lists). Three species are categorized as Critically Endangered, seven as Endangered and 26 as Vulnerable. Our analyses revealed that Elasmobranchii, sex-changing bony fishes and endemic species are the most vulnerable reef fishes in Brazilian waters. Body size and trophic category were identified as good predictors of the vulnerability of a species to extinction. Small-bodied species that are exploited by the ornamental trade and have complex reproductive strategies are also of concern. Such combinations of attributes could be of value in predicting which reef fish species elsewhere have a high risk of extinction."
abstract_short = ""
authors = ["MG Bender", "SR Floeter", "FP Mayer", "DA Vila-Nova", "GO Longo", "N Hanazaki", "A Carvalho-Filho", "CEL Ferreira"]
date = "2013-04-01"
image_preview = ""
math = true
publication_types = ["2"]
publication = "Oryx"
publication_short = "Oryx"
selected = false
title = "Biological attributes and major threats as predictors of the vulnerability of species: a case study with Brazilian reef fishes"
url_code = ""
url_dataset = ""
url_pdf = "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/766F2EC760CAB9530A76D0FBDFE7B631/S003060531100144Xa.pdf/biological_attributes_and_major_threats_as_predictors_of_the_vulnerability_of_species_a_case_study_with_brazilian_reef_fishes.pdf"
url_project = ""
url_slides = ""
url_video = ""

[[url_custom]]
name = "Publication page"
url = "https://doi.org/10.1017/S003060531100144X"

# Optional featured image (relative to `static/img/` folder).
[header]
image = ""
caption = ""

+++
